theme: jekyll-theme-cayman
title: Combustifier
description: We seek your fire, Use Combustifier! This is a major application I was part of developing as part of a course-end project for the AWS Accelerator of 2021.
github:
  is_project_page: false
  repository_url: https://github.com/AWS-Accelerator-Group-3-2021